In [27]:
lista = list(range(0,11))
lista.append('iae')
print(lista)
print(len(lista))
print(lista[len(lista) - 1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'iae']
12
iae


In [31]:
idades = {'João': 10,
          'Ana' : 2,
          'Pedro': 5,
          'Jéssica' : 9}
idades.keys()

dict_keys(['João', 'Ana', 'Pedro', 'Jéssica'])

In [32]:
import numpy as np

In [35]:
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [40]:
#criando array de número inteiros com numpy
#mt = matriz
mtfloat = np.array([12.2, 20.11, 40.56, 44.64], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

#criando array de números flutuantes com numpy
mtint = np.array([1,2,3,4,5], dtype= np.int32)
print(mtint)
print(type(mtint))



[12.2  20.11 40.56 44.64]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [42]:
#mudando tipos de valores nos arrays com numpy

mtnew = np.array([1.2, 4.0, 3, 6.99999])
print(mtnew)


mtnewint = mtnew.astype(np.int32)
mtnewint


[1.2     4.      3.      6.99999]


array([1, 4, 3, 6])

In [2]:
import numpy as np

In [3]:
mt7 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(mt7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
vazio = np.empty([3,2], dtype= int)

print(vazio)

[[667171472       542]
 [558084416       542]
 [667171504       542]]


In [5]:
zeros = np.zeros([4,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
um = np.ones([5,8])
print(um)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [7]:
diagonal = np.eye(5)
print(diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
ale = 10* np.random.random((2,6))
print(ale)

[[7.71943416 4.5216899  5.19352668 5.07462897 9.24011839 8.78800444]
 [7.95460105 2.97167204 1.48851481 1.63311904 3.5047446  7.4592522 ]]


In [13]:
ale2 = np.random.randn((5))
print(ale2)

[0.79617704 0.16470115 0.56795768 1.49948256 0.45765776]


In [17]:
#uso de semente
gnr = np.random.default_rng(1)

ale5 = gnr.random(3)
print(ale5)

[0.51182162 0.9504637  0.14415961]


In [27]:
gnr = np.random.default_rng(1)

ale6 = gnr.integers(60, size=(3,3))
print(ale6)


[[28 30 45]
 [57  2  8]
 [49 56 14]]


In [29]:
#remover repetições nas arrays

j = np.array([1,1,2,2,33,3,4,44,44,7,8,9,10,10,111,111,111,11,1,25,68,45])
j = np.unique(j)
print(j)

[  1   2   3   4   7   8   9  10  11  25  33  44  45  68 111]


In [37]:
k = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(k)
print('----------------')
print(k[2][1])
print('----------------')
print(k.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------
8
----------------
(3, 3)


In [42]:
#funcoes matematicas
m = np.array([1,2,3,4,5,6,7,8,9,10])
print(m)
print('----------------')
print(m[2])
print('----------------')
print(m[0:4])
print('----------------')
print(m[4:])
print('----------------')
print(m[-3])

[ 1  2  3  4  5  6  7  8  9 10]
----------------
3
----------------
[1 2 3 4]
----------------
[ 5  6  7  8  9 10]
----------------
8


In [46]:
l = np.array([[1,2], [4,6], [7,9]])
print(l)
print('----------------')
l_linha_1 = l[0, :]
print(l_linha_1)

[[1 2]
 [4 6]
 [7 9]]
----------------
[1 2]


In [49]:
#adição e multiplicação de matrizes

a = np.array([[1,2], [3,5]])
b = np.array([[1,1], [2,2]])
resultado1 = a + b
print(resultado1)
print('_________')
resultado2 = a * 2
print(resultado2)
print('_________')

[[2 3]
 [5 7]]
_________
[[ 2  4]
 [ 6 10]]
_________


In [53]:
v = np.random.randn(4,4)
print(v)
x = v > 0
print('            ')
print(x)
print('            ')
z = np.where(x > 0, 1, -1)
print(z)


[[-2.01758726 -1.11605943  2.08606285  0.83955908]
 [-0.19212188  0.29502719  0.44401251  0.87353141]
 [-0.39212163 -0.57545686  0.69088102 -0.36308107]
 [ 1.41120987  1.28997813  0.03357405  1.4911931 ]]
            
[[False False  True  True]
 [False  True  True  True]
 [False False  True False]
 [ True  True  True  True]]
            
[[-1 -1  1  1]
 [-1  1  1  1]
 [-1 -1  1 -1]
 [ 1  1  1  1]]
